-- Rollback: Drop all dynamic metric functions
DROP FUNCTION IF EXISTS calculate_stock_return(UUID, INTERVAL, DATE);
DROP FUNCTION IF EXISTS get_stock_returns(INTERVAL, DATE);
DROP FUNCTION IF EXISTS calculate_cagr(UUID, VARCHAR, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS get_metric_cagr(VARCHAR, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS get_price_statistics(UUID, DATE);
DROP FUNCTION IF EXISTS calculate_volatility(UUID, INTERVAL, DATE);
DROP FUNCTION IF EXISTS calculate_yoy_growth(UUID, VARCHAR, INTEGER);
DROP FUNCTION IF EXISTS get_sector_percentile(UUID, VARCHAR, INTEGER);
DROP FUNCTION IF EXISTS get_sector_stats(VARCHAR, VARCHAR, INTEGER);
DROP FUNCTION IF EXISTS calculate_quality_score(UUID, INTEGER);
DROP FUNCTION IF EXISTS calculate_growth_score(UUID, INTEGER, INTEGER);
DROP FUNCTION IF EXISTS calculate_value_score(UUID, INTEGER);
DROP FUNCTION IF EXISTS calculate_pe_avg_10y(UUID, INTEGER);
